services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT:-3003}:5432
    volumes:
      - psql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      retries: 5

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DB_URL=${DB_URL}
    env_file:
      - .env
    ports:
      - ${API_PORT:-3001}:3001
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
        - path: go.mod
          action: rebuild

volumes:
  psql:
