services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT:-3003}:5432
    volumes:
      - psql:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT:-3001}:3001
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
        - path: go.mod
          action: rebuild

volumes:
  psql:
